### ISSUE TITLE
Simple example won't run on Retina DPI

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#11]
This simple example fails to run on a retina machine.
```
deno run -Ar --unstable https://raw.githubusercontent.com/nhrones/Retina/master/retina.ts
```
https://github.com/nhrones/Retina

**Comment by load1n9** [comment]
![image](https://user-images.githubusercontent.com/49134864/211877310-fd06e942-58cf-40bf-8e7a-b1772b7d9963.png)
works for me what error are you getting

**Comment by nhrones** [comment]
dj fixed it! Tanks for looking.
