### ISSUE TITLE
Can't Fetch

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#14]
Is there any reason a fetch call does not work in a DWN app?
When I try to fetch from a localhost server, the promise neither resolves nor rejects?  It seems to be swallowed.

**Comment by DjDeveloperr** [comment]
Any async tasks must be run and awaited under the mainloop function and make sure `loop` argument in mainloop function is set to false.

**Comment by nhrones** [comment]
Thanks for the quick reply.  I understand now.  I'll close this as asked and answered.

**Comment by nhrones** [comment]
Working now! Posting debug messages to a remote logging service that streams to a local debug web page.
Thanks for all you do!
