### ISSUE TITLE
Upgrade Broke apps

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#18]
Deno 0.31.1 has broken all my apps?
I've upgraded skia-canvas to 0.5.2 and that fixed an initial error on start.
Now, I get no input from mouse or keyboard on any of my addEventListeners!

There were no other changes other than the Deno upgrade!

I'll download the DWM demos and try those.  That may help me track down the issue.

**Comment by nhrones** [comment]
Tried to run example cube2.ts and got following error:
```
error: Uncaught (in promise) TypeError: Cannot convert object to primitive value
    return Number(Deno.UnsafePointer.of(v));
           ^
    at Number (<anonymous>)
    at Module.toPointer (https://raw.githubusercontent.com/DjDeveloperr/deno_win32/0.2.0/util.ts:7:12)
    at DwmSetWindowAttribute (https://win32.deno.dev/0.2.0/Graphics.Dwm:775:106)
    at applyMicaAlt (file:///C:/Users/nhron/Desktop/scratch/dwm-main/ext/styles/windows.ts:71:3)
    at file:///C:/Users/nhron/Desktop/scratch/dwm-main/examples/cube2.ts:21:1
```

**Comment by nhrones** [comment]
Example `cursor.ts` works as it should.
example `events.ts` works as exspected.
The IMGUI examples also work?
mouse-capture also OK?

The opengl example errors with:
```
\C:\Users\nhron\Desktop\scratch\dwm-main\examples> run opengl
GlfwError: 65543 WGL: Driver does not support OpenGL ES version 3.2
error: Uncaught Error: Failed to create window
      throw new Error("Failed to create window");
            ^
    at new WindowGlfw (file:///C:/Users/nhron/Desktop/scratch/dwm-main/src/platform/glfw/window.ts:674:13)
    at createWindow (file:///C:/Users/nhron/Desktop/scratch/dwm-main/src/platform/mod.ts:43:10)

    at file:///C:/Users/nhron/Desktop/scratch/dwm-main/examples/opengl.ts:4:16
```
Looks like you have a GUI (IMGUI) example!  I'll just park mine and watch yours.

**Comment by nhrones** [comment]
Can't use close button on Windows!  Can't close the window from the taskbar menu?

**Comment by load1n9** [comment]
update dwm latest update should have fixed it

**Comment by load1n9** [comment]
did you try refreshing the cache

**Comment by jakehl** [comment]
I did. I updated Deno to canary and it works, downgrading to stable again gives the same error.

**Comment by nhrones** [comment]
I'll just wait for canary to drop to stable

**Comment by nhrones** [comment]
Updating to dwm-latest has fixed all my issues.  
Thanks again guys.  Your the best!

**Comment by nhrones** [comment]
@jakehl   Try running your app with `Deno run -Ar` to force a refresh.
