### ISSUE TITLE
MouseMove

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#2]
Is there a way to get mouse events in a canvasWindow? (the cube example)?
I've tried addEventListener on  the `win.window` object and the `win.canvas` object in the `cube` example with no luck.
What am I missing?

Also, resizing the canvas seems to have no effect?  A `clearRect()` or `fillRect()` always paints the whole window, not just the canvas area? Although other paths rendered are actually clipped to the new canvas size>

**Comment by nhrones** [comment]
I found what I needed!  The `loop` and `wait` options of the `mainLoop` call, unblock events.

Thanks again! Keep up the good work.

**Comment by DjDeveloperr** [comment]
Btw you need to use global addEventListener function instead of on window or canvas.

**Comment by nhrones** [comment]
Yes! discovered that. Thanks!
