### ISSUE TITLE
broke again

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#21]
I upgraded Deno to 1.32.3 and now once again none of my dwm projects are working.
```
error: Module not found "https://glfw-binaries.deno.dev/3.4.0-patch1/glfw3_darwin.js".
    at https://deno.land/x/dwm@0.3.2/src/platform/glfw/ffi.ts:2:20
```
I just wanted to report this to you.  I am no longer interested in this project. 
I'll probably revert all my efforts back to Node, as Deno is like digging a ditch in dry sand.

**Comment by DjDeveloperr** [comment]
@load1n9 did something happen to patch1 release of build-glfw? Seems to have broken some code using previous version of dwm.

**Comment by DjDeveloperr** [comment]
And btw, this issue is not a problem related to Deno but something on our end.
