### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#26]
Once again, none of my DWM apps work.  Can't tell what's changed, but the error is as follows:
```
Executing task: deno run -A --unstable main.ts 

error: Uncaught Error: Could not open library: The specified module could not be found.

  mod = Deno.dlopen(tmp, symbols);
             ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:577:10)
    at https://deno.land/x/dwm@0.3.3/src/platform/glfw/ffi.ts:463:14
```

**Comment by jcpsimmons** [comment]
Run with `--unstable`

**Comment by jcpsimmons** [comment]
<img width="283" alt="image" src="https://github.com/deno-windowing/dwm/assets/6600962/9f00b37a-8db3-4e47-9bf4-ffc3e9364eeb">

**Comment by DjDeveloperr** [comment]
The example off readme works fine on macOS for me. Can you provide more details?

**Comment by nhrones** [comment]
Can't recreate the error?  Works fine for now. Closing
