### ISSUE TITLE
Add rawHandle() API

### ISSUE THREAD

**Issue by littledivy** [deno-windowing/dwm#29]
Ability to retrieve the window and display/instance handles from glfw. Similar to deno_sdl2's `Window#rawHandle()`.

Rust implementation for reference: https://github.com/PistonDevelopers/glfw-rs/blob/2221cf05410c3dd2fac6f711c8f28e072c16f1fb/src/lib.rs#L3518

```typescript
  /**
   * Return the raw handle of the window.
   *
   * platform: "cocoa" | "win32" | "winrt" | "x11" | "wayland"
   *
   * ```ts
   * const [platform, handle, display] = window.rawHandle();
   * ```
   *
   * on macOS:
   * - platform: "cocoa"
   * - handle: NSWindow
   * - display: NSView
   *
   * on Windows:
   * - platform: "win32" | "winrt"
   * - handle: HWND
   * - display: null | HINSTANCE
   *
   * on Linux:
   * - platform: "x11" | "wayland"
   * - handle: Window
   * - display: Display
   */
  rawHandle(): [string, Deno.PointerValue, Deno.PointerValue | null];
```

This can be passed to Deno's WebGPU with this proposal: https://github.com/denoland/deno/issues/21713

**Comment by load1n9** [comment]
Sounds good!

**Comment by nhrones** [comment]
Any progress here?  I'm interested in porting my DWM-ReativeUI framewowk from Skia-Canvas to WebGPU.  

What would it take to use DWM as the BYOW for Deno-WebGPU?  Is anyone working on this?
