### ISSUE TITLE
audio context

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#3]
Are there any plans to support an audio context for this windowing lib?

**Comment by DjDeveloperr** [comment]
Yes. I think we’d make a separate module for that (under Deno Windowing project however). It would also ideally follow Web Standard API.

**Comment by nhrones** [comment]
Thanks.  I'll wait patiently.  Let me know if I can help with any testing(Windows10).
Also, I noticed that `click`, and `bublclick` did not work for me. Again on Win10.

**Comment by DjDeveloperr** [comment]
> Also, I noticed that click, and bublclick did not work for me. Again on Win10.

Please open a separate issue, I'll investigate when I get time. Preferably, also add minimum reproducible example.
