### ISSUE TITLE
op_base64_decode is not a function

### ISSUE THREAD

**Issue by sudokit** [deno-windowing/dwm#31]
So yesterday, i ran the same code, with the same version of deno (`deno 1.39.4 (release, x86_64-pc-windows-msvc) v8 12.0.267.8 typescript 5.3.3`), with the same version of windows, and everything, and it ran fine. Today i tried running it again... Aaaand:
```
error: Uncaught (in promise) TypeError: Deno[Deno.internal].core.ops.op_base64_decode is not a function
    at https://glfw-binaries.deno.dev/3.4.0-patch2/glfw3_windows.js:2:108
```
I am really confused... The line the error is referencing looks like this:
```typescript
const DECODED = Deno.build.os === "windows" && Deno.build.arch === "x86_64" ? Deno[Deno.internal].core.ops.op_base64_decode(BASE64) : new Uint8Array();
````
so just trying to decode the base64 encoded thingy. But for some reason today it thinks that core.ops.op_base64_decode isnt a function... eh?

EDIT: example code in question:
```typescript
import * as gl from "https://deno.land/x/gluten@0.1.6/api/gles23.ts";
import {
    CanvasRenderingContext2D,
    getProcAddress,
    mainloop,
    WindowCanvas,
} from "https://deno.land/x/dwm@0.3.3/ext/canvas.ts";
import {
      createContext,
      destroyContext,
      imgui,
} from "https://deno.land/x/dwm@0.3.3/ext/imgui.ts";

const WIDTH = 800;
const HEIGHT = 600;

let deltatime = 0;

const canvas = new WindowCanvas({
      title: "Skia Canvas",
      width: WIDTH,
      height: HEIGHT,
      resizable: false,
});
gl.load(getProcAddress);

const imguiContext = createContext(canvas.window);
imgui.implOpenGL3NewFrame();

addEventListener("close", () => {
      destroyContext(imguiContext);
});


canvas.onDraw = (ctx: CanvasRenderingContext2D) => {
    gl.Clear(gl.COLOR_BUFFER_BIT);
}

const UI = () => {
    imgui.implGlfwNewFrame();
    imgui.newFrame();
    imgui.begin("Quadtree");
    imgui.text(`deltatime: ${deltatime.toFixed(5)}`);
    imgui.text(`fps: ${(10 / deltatime).toFixed(2)}`);
    imgui.end();

    imgui.render();
    const drawData = imgui.getDrawData();
    imgui.implOpenGL3RenderDrawData(drawData);
}

await mainloop(() => {
    const t0 = performance.now();
    canvas.draw();
    UI();
    deltatime = (performance.now() - t0) / 1000;
    console.log(`fps: ${(1 / deltatime).toFixed(2)}`);
});
````
ran with the command: ```deno run --unstable -A --check --watch .\main.ts```

**Comment by load1n9** [comment]
what happens if you remove the --check?

**Comment by sudokit** [comment]
Same thing:
```
❯ deno run --unstable -A --watch main.ts
Watcher Process started.
error: Uncaught (in promise) TypeError: Deno[Deno.internal].core.ops.op_base64_decode is not a function
    at https://glfw-binaries.deno.dev/3.4.0-patch2/glfw3_windows.js:2:108
Watcher Process failed. Restarting on file change...
```
same thing without ```--watch```
same thing with ```--unstable --allow-ffi --allow-write --allow-env``` (btw deno also needs --allow-read:
```
┌ ⚠️  Deno requests read access to "C:\Users\user\AppData\Local\deno\plug".
├ Requested by `Deno.lstat()` API.
├ Run again with --allow-read to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all read permissions) >
```
)

**Comment by load1n9** [comment]
what happens if you upgrade to a stable release?

**Comment by sudokit** [comment]
Isnt 1.39.4 a stable release? Doing:
```
❯ deno upgrade
Looking up latest version
Local deno version 1.39.4 is the most recent release
```
I doubt its related to the version, bc it worked with the same version before...

**Comment by DjDeveloperr** [comment]
Not sure why these ops disappeared. But after all it's internals and we shouldn't depend on those. It's the only fast way to decode base64 though.

**Comment by sudokit** [comment]
> Not sure why these ops disappeared. But after all it's internals and we shouldn't depend on those. It's the only fast way to decode base64 though.

i mean i dont think theres really anything wrong on depending on those 🤷‍♂️ especially if its the fastest way and well its already usable. 

> what's weird is that the ops are accessable through the deno repo but not when run there must be some flag

but yeah its really perplexing as to why it just suddenly idk poof gone :p. idk what to blame either? is anyone else able to reproduce it or is it only on my latpop? if yes then i prob should try reinstalling deno... idfk whats going onnnn

**Comment by sudokit** [comment]
Ahhhh... That sucks :/ and yeah its visible in the REPL (checked it bc had to be sure that it just hadnt disappeared completely :pp)

**Comment by sudokit** [comment]
Soo uhh what to do?

**Comment by sudokit** [comment]
I see @load1n9 added a possible [patch](https://github.com/deno-windowing/build-glfw/commit/5152c24d2dd6232fdeef490f5c27afdd4e77b8df) for this. Havent tried it out yet, but hopefully it will work. Thanks!!
