### ISSUE TITLE
Doesn't work in Web Worker

### ISSUE THREAD

**Issue by Mutefish0** [deno-windowing/dwm#36]
I encountered an error when using dwn in a Web Worker.

Deno version:
```
deno 1.46.3 (stable, release, aarch64-apple-darwin)
```
### Steps to Reproduce
create `main.js`:
```js
new Worker(import.meta.resolve("./worker.js"), {
  type: "module",
});
```
create `worker.js`:
```js
import { createWindow } from "https://deno.land/x/dwm@0.3.6/mod.ts";
console.log(createWindow);
```
run:
```
deno run --unstable-ffi main.js
```

then you will get this error: 
```
2024-09-17 19:03:12.057 deno[71161:1360199] *** Assertion failure in -[NSMenu _setMenuName:], NSMenu.m:777
```

**Comment by DjDeveloperr** [comment]
Looks like you're on macOS - macOS or any Apple platform in general does not allow UI from non-main thread. So dwm will always crash when used from a worker

**Comment by Mutefish0** [comment]
Understood, thanks for the clarification!
