### ISSUE TITLE
error while running example from Windows 11

### ISSUE THREAD

**Issue by 77it** [deno-windowing/dwm#7]
environment: Windows 11 (without WSL) and deno version 1.29.1 (release, x86_64-pc-windows-msvc)

problem: running the example code found on the [readme page](https://github.com/deno-windowing/dwm/blob/74add7f721bfb40b3d65c911191383458e306764/README.md#example) with the command `deno run --unstable --allow-ffi --allow-env --allow-write` I get the error 

> error: Uncaught (in promise) ReferenceError: instancePointer is not defined
> const surfaceKHR = win.createSurface(instancePointer);

I'm no expert about GUI and JavaScript, but reading that dwm was cross platform I decided to try it on Windows, without luck.

**Comment by DjDeveloperr** [comment]
The code in readme is not a complete example but a demonstration of basic APIs to get a window up and running using different renderer backends. Surface creation is only required for Vulkan API which  accepts instance pointer made by https://github.com/deno-windowing/vulkan (it has examples in the repo).
For complete examples, see `examples/` dir.

**Comment by DjDeveloperr** [comment]
Improved examples in readme. They should work out of the box now if you copy paste them, even into REPL for example.
